---
# Variables for OCR role
install_root: "{{ courtlistener_directory }}"
log_directory: /var/log/courtlistener
juriscraper_log_directory: /var/log/juriscraper

phantomjs_version: 2.1.1
phantomjs_symlink_root: /usr/local/bin
