########################
#  Install Tesseract
########################
---
- debug: msg="Installing Tesseract v{{ tesseract_version}}..."

- name: configure ocr build directory
  become_user: root
  file:
    state=directory
    path="{{ src_directory }}"
    owner="{{ ocr_user }}"
    group="{{ ocr_user }}"

- name: download and unpack tesseract
  become_user: "{{ ocr_user }}"
  unarchive:
    src="{{ tesseract_url }}"
    dest="{{ src_directory }}"
    copy=no
    owner="{{ ocr_user }}"
    group="{{ ocr_user }}"
    creates="tesseract-{{ tesseract_version }}"

- name: download tessdata for our default language
  become_user: "{{ ocr_user }}"
  get_url:
    url="{{ tessdata_url }}/{{ item }}"
    dest="{{ src_directory }}/tesseract-{{ tesseract_version }}/tessdata"
  with_items: "{{ tesseract_lang_data }}"

- name: make tessearct
  become_user: "{{ ocr_user }}"
  command: "{{ item }}"
  args:
    chdir: "{{ src_directory }}/tesseract-{{ tesseract_version }}"
    creates:
      - "{{ src_directory }}/tesseract-{{ tesseract_version }}/api/tesseract"
      - - /usr/local/lib/liblept.so
  with_items:
    - ./configure
    - make

- name: install tessearct
  become_user: root
  command: "{{ item }}"
  args:
    chdir: "{{ src_directory }}/tesseract-{{ tesseract_version }}"
    creates:
      - /usr/local/bin/tesseract
      - /usr/local/lib/libtesseract.so
  with_items:
    - make install
    - ldconfig
