#!/usr/bin/env ansible-playbook
---
# Build out a FreeLawMachine from an Ubuntu Trusty64 Vagrantbox
- hosts: dev
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    courtlistener_directory: /var/www/courtlistener
    cl_pg_password: courtlistener
    virtualenv_directory: /home/vagrant/.virtualenvs/courtlistener
    celery_user: vagrant
    redis_user: vagrant
    pg_user: vagrant
    solr_user: vagrant
    solr_version: 4.1.0
  roles:
    - ubuntu-trusty
    - vagrantbox
    - redis
    - celery
    - postgres
    - solr
